### ISSUE TITLE
New fixes available upstream

### ISSUE THREAD

**Issue by roubert** [ghuysmans/jdbcldap#3]
I've recently contributed some fixes upstream, which you might be interested in pulling into your fork:

https://git.openldap.org/openldap/jdbcldap/-/commits/master/

**Comment by ghuysmans** [comment]
Thanks for the heads-up! By the way, are you interested in patches like [this one](https://github.com/ghuysmans/jdbcldap/commit/224e87b24a5b62c192a4583921d110b8ce539e59)?

**Comment by roubert** [comment]
I am myself just a random contributor who fixed a few things that I needed for myself, but my experience with these fixes that I just contributed was that the upstream maintainers appreciated receiving fixes:

https://www.openldap.org/devel/contributing.html

**Comment by ghuysmans** [comment]
Alright, I'll consider pushing those upstream. Thanks again!
